text_sensor:
  - platform: homeassistant
    id: dial_light_sofa_state
    entity_id: light.sofa
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_mesa_state
    entity_id: light.mesa
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_jardin_state
    entity_id: light.luces_jardin
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_sofa_modes
    entity_id: light.sofa
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_modes
    entity_id: light.mesa
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_modes
    entity_id: light.luces_jardin
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_sofa_rgb
    entity_id: light.sofa
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_rgb
    entity_id: light.mesa
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_rgb
    entity_id: light.luces_jardin
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_sofa_color_mode
    entity_id: light.sofa
    attribute: color_mode
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_color_mode
    entity_id: light.mesa
    attribute: color_mode
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_color_mode
    entity_id: light.luces_jardin
    attribute: color_mode
    internal: true

sensor:
  - platform: homeassistant
    id: dial_light_sofa_brightness
    entity_id: light.sofa
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_mesa_brightness
    entity_id: light.mesa
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_jardin_brightness
    entity_id: light.luces_jardin
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_sofa_color_temp_kelvin
    entity_id: light.sofa
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_color_temp_kelvin
    entity_id: light.mesa
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_color_temp_kelvin
    entity_id: light.luces_jardin
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_sofa_min_color_temp_kelvin
    entity_id: light.sofa
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_min_color_temp_kelvin
    entity_id: light.mesa
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_min_color_temp_kelvin
    entity_id: light.luces_jardin
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_sofa_max_color_temp_kelvin
    entity_id: light.sofa
    attribute: max_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_mesa_max_color_temp_kelvin
    entity_id: light.mesa
    attribute: max_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_jardin_max_color_temp_kelvin
    entity_id: light.luces_jardin
    attribute: max_color_temp_kelvin
    internal: true
